
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author liamsi
 */
public class Avis extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_des_notes
     */
    static Connection con;
    Connecter conn=new Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model=new DefaultTableModel();
    public Avis() {
        initComponents();
              
model.addColumn("avis");
model.addColumn("contenu");
model.addColumn("date affichage");
model.addColumn("date retir ");
model.addColumn("filiere");
model.addColumn("catégorie");
try {
stm=conn.obtenirconnexion().createStatement();
ResultSet Rs=stm.executeQuery("Select * from avis");
while(Rs.next()){
model.addRow(new Object[]{Rs.getString("id_avis"),Rs.getString("contenu"),Rs.getString("date_aff"),
    Rs.getString("date_ret"),Rs.getString("filiere"),Rs.getString("categorie")});

}
}catch(Exception e){System.err.println(e);}

tble.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcon = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dateretir = new javax.swing.JSpinner();
        dateaff = new javax.swing.JSpinner();
        combfiliere = new javax.swing.JComboBox();
        combcateg = new javax.swing.JComboBox();
        btnAjout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(770, 530));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel6.setText("gestion des avis");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 30, 350, 70);

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(314, 140, 400, 90);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("id :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 42, 17);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Contenu ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 150, 90, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("date affichage:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 190, 91, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("date de retir :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 240, 85, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Filiere  :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 280, 60, 17);

        txtcon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconActionPerformed(evt);
            }
        });
        getContentPane().add(txtcon);
        txtcon.setBounds(170, 150, 120, 23);

        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid);
        txtid.setBounds(170, 110, 120, 23);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Catégorie");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 320, 60, 17);
        getContentPane().add(dateretir);
        dateretir.setBounds(170, 240, 120, 20);
        getContentPane().add(dateaff);
        dateaff.setBounds(170, 190, 120, 20);

        combfiliere.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Informatique", "Genie civil ", "Telecom" }));
        combfiliere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combfiliereActionPerformed(evt);
            }
        });
        getContentPane().add(combfiliere);
        combfiliere.setBounds(180, 280, 110, 20);

        combcateg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administration ", "Enseignement" }));
        combcateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combcategActionPerformed(evt);
            }
        });
        getContentPane().add(combcateg);
        combcateg.setBounds(180, 320, 110, 20);

        btnAjout.setText("Ajout");
        btnAjout.setActionCommand("Ajout");
        btnAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjout);
        btnAjout.setBounds(130, 370, 59, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void deplace(int i){
try {
txtid.setText(model.getValueAt(i,0).toString());
txtcon.setText(model.getValueAt(i,1).toString());
dateaff.getValue();
dateretir.getValue();
combfiliere.setSelectedItem(model.getValueAt(i,3).toString());
combcateg.setSelectedItem(model.getValueAt(i,4).toString());

}catch (Exception e){System.err.println(e);
JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());}
}

private void afficher(){
try {
    model.setRowCount(0);
stm=conn.obtenirconnexion().createStatement();
ResultSet Rs=stm.executeQuery("Select * from avis");
while(Rs.next()){
model.addRow(new Object[]{Rs.getString("id_avis"),Rs.getString("contenu"),Rs.getString("date_aff"),
    Rs.getString("date_ret"),Rs.getString("id_filiere"),Rs.getString("id_cat")});

}
}catch(Exception e){System.err.println(e);}

tble.setModel(model);
}
    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
try{
int i=tble.getSelectedRow();deplace(i);
}catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de deplacement "+e.getLocalizedMessage());}
    }//GEN-LAST:event_tbleMouseClicked

    private void combcategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combcategActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combcategActionPerformed

    private void combfiliereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combfiliereActionPerformed
      
     
    }//GEN-LAST:event_combfiliereActionPerformed

    private void txtconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconActionPerformed

    private void btnAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Avis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Avis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Avis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Avis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Avis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjout;
    private javax.swing.JComboBox combcateg;
    private javax.swing.JComboBox combfiliere;
    private javax.swing.JSpinner dateaff;
    private javax.swing.JSpinner dateretir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tble;
    private javax.swing.JTextField txtcon;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
